#!/usr/bin/env bash
# Copyright (c) 2016 The UUV Simulator Authors.
# All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Get salinity using input position wrt NED reference frame"
rosservice call /nc_data/interpolate_nc_data "point:
  x: 0.0
  y: 0.0
  z: 3.0
geo_point:
  latitude: 0.0
  longitude: 0.0
  altitude: 0.0
reference_frame_convention: 'ned'
variable: 'salinity'
time: 0.0"

echo "Get salinity using input position wrt ENU reference frame"
rosservice call /nc_data/interpolate_nc_data "point:
  x: 0.0
  y: 0.0
  z: -5.0
geo_point:
  latitude: 0.0
  longitude: 0.0
  altitude: 0.0
reference_frame_convention: 'enu'
variable: 'salinity'
time: 0.0"

echo "Get salinity using input position wrt geodetic (WGS84) reference frame"
rosservice call /nc_data/interpolate_nc_data "point:
  x: 0.0
  y: 0.0
  z: 0.0
geo_point:
  latitude: 56.71898669633431
  longitude: 3.515625
  altitude: -4.5
reference_frame_convention: 'wgs84'
variable: 'salinity'
time: 0.0"
